language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - wget https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2
  - tar xvf samtools-1.2.tar.bz2
  - cd samtools-1.2
  - make
  - cd ..
  - export PATH="samtools-1.2:$PATH"
  - case "$TRAVIS_PYTHON_VERSION" in
    2*)
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      PYTHON="python"
      ;;
    3*)
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      PYTHON="python3"
      ;;
    esac
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # add bioconda channels 
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda create -q -n sufam-env
    --file requirements.txt pip nose
  - source activate sufam-env
  - pip install -e .
script:
  - source activate sufam-env
  - nosetests
