language: python
python:
  - "2.7"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq samtools
  - sudo pip install conda
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas requests nose numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - python setup.py install
script:
  - nosetests
